################################################################################
# Metrics and sensitivity analysis script
# Script: 30_metrics.R
################################################################################

source("00_functions.R", local = TRUE)

################################################################################
# Configuration
################################################################################

n_boot <- 2000

# Parameters for power subset calculation
target_power <- 0.80
grid_res <- 30
tij_max <- 0.25  
n_max <- 250

# Parameters for null distribution usage
# (redundant for global metrics without reduction, kept in case a full nominal analysis is needed)
use_threshold_ior <- TRUE
use_threshold_reri <- TRUE

# Classification of high-reporting stages by dynamic pattern
stage_class <- rbind(
  data.table(nichd = niveles_nichd, dynamic = "uniform", class = 1),
  data.table(nichd = niveles_nichd, dynamic = "increase", class = c(0, 0, NA, NA, NA, 1, 1)),
  data.table(nichd = niveles_nichd, dynamic = "decrease", class = c(1, 1, NA, NA, NA, 0, 0)),
  data.table(nichd = niveles_nichd, dynamic = "plateau", class = c(0, NA, 1, 1, 1, NA, 0)),
  data.table(nichd = niveles_nichd, dynamic = "inverse_plateau", class = c(1, NA, 0, 0, 0, NA, 1))
)

# Paths
ruta_base_sensitivity <- paste0("./results/", suffix, "/augmentation_results/")
output_dir <- paste0("./results/", suffix, "/metrics_results/")

ruta_coadmin_pos <- paste0("./results/", suffix, "/augmentation_results/positive_coadmin_by_stage.csv")
ruta_coadmin_neg <- paste0("./results/", suffix, "/augmentation_results/negative_coadmin_by_stage.csv")

dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)

# Reduction levels
reduction_levels <- c(0, seq(10, 90, by = 10))

################################################################################
# Plot labels
################################################################################

# Labels for plot display
dynamic_labels <- c(
  "uniform" = "Uniforme",
  "increase" = "Incremento",
  "decrease" = "Disminución",
  "plateau" = "Meseta",
  "inverse_plateau" = "Valle"
)

nichd_labels <- c(
  "term_neonatal" = "Neonato a término",
  "infancy" = "Lactante",
  "toddler" = "Deambulador",
  "early_childhood" = "Preescolar",
  "middle_childhood" = "Escolar",
  "early_adolescence" = "Adolescencia temprana",
  "late_adolescence" = "Adolescencia tardía"
)

metrics_to_plot <- c("sensitivity", "specificity", "PPV", "NPV", "F1")
metric_labels <- c(
  "sensitivity" = "Sensibilidad",
  "specificity" = "Especificidad",
  "PPV" = "Valor Predictivo Positivo",
  "NPV" = "Valor Predictivo Negativo",
  "F1" = "F1-Score"
)

method_pairs <- list(
  list(gam = "GAM-logIOR", classic = "Estratificado-IOR", label = "IOR"),
  list(gam = "GAM-RERI", classic = "Estratificado-RERI", label = "RERI")
)

################################################################################
# Loading null thresholds
################################################################################

ruta_null_dist <- paste0("./results/", suffix, "/null_distribution_results/null_distribution.csv")
thresh_col <- paste0("threshold_", percentil)

# GAM null thresholds
null_thresholds_ior <- fread(paste0("./results/", suffix, "/null_distribution_results/null_thresholds.csv"))
null_thresholds_ior <- null_thresholds_ior[, .(stage, threshold_ior = get(thresh_col))]

null_thresholds_reri <- fread(paste0("./results/", suffix, "/null_distribution_results/null_thresholds_reri.csv"))
null_thresholds_reri <- null_thresholds_reri[, .(stage, threshold_reri = get(thresh_col))]

# Classic null thresholds (generated by 20_null.R) — optional: fallback to NA if not present
ruta_cls_ior  <- paste0("./results/", suffix, "/null_distribution_results/null_thresholds_classic_ior.csv")
ruta_cls_reri <- paste0("./results/", suffix, "/null_distribution_results/null_thresholds_classic_reri.csv")

classic_null_available <- file.exists(ruta_cls_ior) && file.exists(ruta_cls_reri)

if (classic_null_available) {
  null_thresholds_cls_ior <- fread(ruta_cls_ior)[, .(stage, threshold_classic_ior = get(thresh_col))]
  null_thresholds_cls_reri <- fread(ruta_cls_reri)[, .(stage, threshold_classic_reri = get(thresh_col))]
  message("Classic null thresholds loaded")
} else {
  warning("Classic null threshold files not found — stratified methods will run in nominal mode only")
  null_thresholds_cls_ior <- data.table(stage = 1:7, threshold_classic_ior  = NA_real_)
  null_thresholds_cls_reri <- data.table(stage = 1:7, threshold_classic_reri = NA_real_)
}

# Merge all four threshold columns into a single table joined on stage
null_thresholds <- merge(null_thresholds_ior, null_thresholds_reri, by = "stage")
null_thresholds <- merge(null_thresholds, null_thresholds_cls_ior, by = "stage")
null_thresholds <- merge(null_thresholds, null_thresholds_cls_reri, by = "stage")

################################################################################
# Loading baseline data (no reduction)
################################################################################

data_baseline <- expand(0)  # load unreduced data for power threshold calculations
pos_high_base <- data_baseline$pos_high
neg_high_base <- data_baseline$neg_high

################################################################################
# Distribution comparison plots
################################################################################

null_distribution <- fread(ruta_null_dist)

# sample null distribution for plotting
null_sample <- null_distribution[sample(.N, min(.N, 50000))]

comparison_data <- rbind(
  null_sample[, .(stage_num = stage, log_ior_lower90 = log_lower90, reri_lower90 = reri_lower90, source = "Distribución nula")],
  pos_high_base[, .(stage_num, log_ior_lower90 = gam_log_ior_lower90, reri_lower90 = gam_reri_lower90, source = "Positivos")],
  neg_high_base[, .(stage_num, log_ior_lower90 = gam_log_ior_lower90, reri_lower90 = gam_reri_lower90, source = "Negativos")]
)
comparison_data[, stage_name := factor(stage_num, levels = 1:7, labels = nichd_labels)] # ordered for facet display

# trim data for plotting (could alternatively be handled via axis limits in the plot)
comparison_data <- comparison_data[ is.finite(log_ior_lower90)]
comparison_data <- comparison_data[ is.finite(reri_lower90)]

# Consistent color palette
color_palette <- c(
  "Distribución nula" = "gray60",
  "Positivos" = "#4DAF4A",
  "Negativos" = "#E41A1C"
)

# Combined faceted plot
p_null_vs_obs_ior <- ggplot( comparison_data, aes(x = log_ior_lower90, fill = source)) +
  geom_density(alpha = 0.5, adjust = 1.5) +
  facet_wrap(~ stage_name, scales = "free_y", ncol = 4) +
  scale_fill_manual(values = color_palette) +
  scale_x_continuous(limits = c(-5, 5)) + # clipped to improve distribution visibility
  labs(
    title = sprintf("Distribución nula vs señales detectadas (%s)", percentil),
    x = "Log(IOR) - Límite inferior IC 90%",
    y = "Densidad",
    fill = "Fuente")
  # Save combined plot
  ggsave(paste0(output_dir, "fig_null_vs_observed_ior.png"), p_null_vs_obs_ior, width = 16, height = 12, dpi = 300
)

print(p_null_vs_obs_ior)

# Combined faceted plot
p_null_vs_obs_reri <- ggplot( comparison_data, aes(x = reri_lower90, fill = source)) +
  geom_density(alpha = 0.5, adjust = 1.5) +
  facet_wrap(~ stage_name, scales = "free_y", ncol = 4) +
  scale_fill_manual(values = color_palette) +
  scale_x_continuous(limits = c(-10, 10)) +  # clipped to improve distribution visibility
  labs(
    title = sprintf("Distribución nula vs señales detectadas (%s)", percentil),
    x = "RERI - Límite inferior IC 90%",
    y = "Densidad",
    fill = "Fuente"
  ) 
# Save combined plot
ggsave( paste0(output_dir, "fig_null_vs_observed_reri.png"), p_null_vs_obs_reri, width = 16, height = 12, dpi = 300)

print(p_null_vs_obs_reri)

message(sprintf("Dataset base: %d positivos, %d negativos", nrow(pos_high_base), nrow(neg_high_base)))

################################################################################
# Power subset calculation for each method
################################################################################

# GAM-logIOR
message("GAM-logIOR")
power_gam_ior <- calculate_power_gam(
  data_pos = pos_high_base,
  target_power = target_power,
  null_thresholds = null_thresholds,
  metric_n = "n_coadmin",
  grid_resolution = grid_res,
  use_threshold_ior = TRUE,
  use_threshold_reri = FALSE,
  detection = "ior"
)

# GAM-RERI
message("GAM-RERI")
power_gam_reri <- calculate_power_gam(
  data_pos = pos_high_base,
  target_power = target_power,
  null_thresholds = null_thresholds,
  metric_n = "n_coadmin",
  grid_resolution = grid_res,
  use_threshold_ior = FALSE,
  use_threshold_reri = TRUE,
  detection = "reri"
)

# Stratified-IOR
message("Estratificado-IOR")
power_cls_ior <- calculate_power_classic(
  data_pos = pos_high_base,
  target_power = target_power,
  null_thresholds = NULL,
  metric_n = "n_coadmin_stage",
  grid_resolution = grid_res,
  detection = "ior",
  na_remove = TRUE
)

# Stratified-RERI
message("Estratificado-RERI")
power_cls_reri <- calculate_power_classic(
  data_pos = pos_high_base,
  target_power = target_power,
  null_thresholds = NULL,
  metric_n = "n_coadmin_stage",
  grid_resolution = grid_res,
  detection = "reri",
  na_remove = TRUE
)

power_ior_list <- list(
  "GAM" = power_gam_ior,
  "Estratificado" = power_cls_ior
)

p_surface_ior <- plot_power_surface(
  power_results_list = power_ior_list,
  target_power = target_power, 
  detection = "IOR",
  grid_size = grid_res,
  t_range = c(0, tij_max), 
  n_range = c(0, n_max)
)

ggsave(
  paste0(output_dir, "fig_power_surface_ior_combined.png"), 
  p_surface_ior,
  width = 14,      
  height = 7,     
  dpi = 300
)

print(p_surface_ior)

power_reri_list <- list(
  "GAM" = power_gam_reri,
  "Estratificado" = power_cls_reri
)

p_surface_reri <- plot_power_surface(
  power_results_list = power_reri_list,
  target_power = target_power,
  detection = "RERI", 
  grid_size = grid_res,
  t_range = c(0, tij_max),
  n_range = c(0, n_max)
)

ggsave(
  paste0(output_dir, "fig_power_surface_reri_combined.png"),
  p_surface_reri, 
  width = 14,
  height = 7,
  dpi = 300
)

print(p_surface_reri)

# Store triplet IDs for each power subset
power_ids <- list(
  "GAM-logIOR" = unique(power_gam_ior$superset_pos[class == 1]$triplet_id),
  "GAM-RERI" = unique(power_gam_reri$superset_pos[class == 1]$triplet_id),
  "Estratificado-IOR" = unique(power_cls_ior$superset_pos[class == 1]$triplet_id),
  "Estratificado-RERI" = unique(power_cls_reri$superset_pos[class == 1]$triplet_id)
)

# Map null-stratified methods to their nominal power subsets
# (power thresholds computed on nominal criterion; null threshold is detection-only)
power_ids[["Estratificado-IOR_null"]] <- power_ids[["Estratificado-IOR"]]
power_ids[["Estratificado-RERI_null"]] <- power_ids[["Estratificado-RERI"]]
power_ids[["GAM-logIOR_nom"]] <- power_ids[["GAM-logIOR"]]
power_ids[["GAM-RERI_nom"]] <- power_ids[["GAM-RERI"]]


# Intersection subsets - triplets that meet the power threshold for both methods in a pair
triplets_intersection_reri <- intersect(power_ids[["GAM-RERI"]], power_ids[["Estratificado-RERI"]])
message(sprintf("\nIntersección GAM-RERI & Estratificado-RERI: %d tripletes", length(triplets_intersection_reri)))

triplets_intersection_ior <- intersect(power_ids[["GAM-logIOR"]], power_ids[["Estratificado-IOR"]])
message(sprintf("\nIntersección GAM-logIOR & Estratificado-IOR: %d tripletes", length(triplets_intersection_ior)))

# Power subset summary
summary_power <- data.table(
  method = names(power_ids),
  n_triplets = sapply(power_ids, length),
  t_star = c(power_gam_ior$t_star, power_gam_reri$t_star,
             power_cls_ior$t_star, power_cls_reri$t_star),
  n_star = c(power_gam_ior$n_star, power_gam_reri$n_star,
             power_cls_ior$n_star, power_cls_reri$n_star)
)
print(summary_power)

################################################################################
# Data with downsampling
################################################################################

# Pre-load all reduction levels into memory at once
datos_por_reduccion <- lapply(reduction_levels, expand)
names(datos_por_reduccion) <- as.character(reduction_levels)

################################################################################
# Exclusion of triplets that become undetectable after downsampling
################################################################################

# A triplet with N = 0 A-B-Event reports in the reduced dataset no longer exists:
# classifying it as negative reflects trivial absence, not method performance.
# Including such triplets artificially inflates specificity and NPV at high reduction levels.

exclude_downsampled <- TRUE   

if (exclude_downsampled) {
  
  datos_por_reduccion <- lapply(names(datos_por_reduccion), function(red) {
    datos <- datos_por_reduccion[[red]]
    
    n_neg_antes <- uniqueN(datos$neg_high$triplet_id)
    n_pos_antes <- uniqueN(datos$pos_high$triplet_id)
    
    # Negatives: exclude triplets with no A-B-Event reports
    datos$neg_high <- datos$neg_high[N > 1]
    # Positives: same logic (injected signals typically have N > 0, but kept for consistency)
    datos$pos_high <- datos$pos_high[N > 1]
    
    n_neg_excluidos <- n_neg_antes - uniqueN(datos$neg_high$triplet_id)
    n_pos_excluidos <- n_pos_antes - uniqueN(datos$pos_high$triplet_id)
    
    message(sprintf(
      " Reducción %s%%: excluidos %d negativos + %d positivos (N = 0)",
      red, n_neg_excluidos, n_pos_excluidos
    )) 
    datos
  })
  names(datos_por_reduccion) <- as.character(reduction_levels)
}

################################################################################
# Method definitions
################################################################################

# Methods with their mapped score types and detection settings
metodos <- list(
  # GAM with null distribution threshold
  list(nombre = "GAM-logIOR", tipo = "IOR", null = TRUE,
       score_type = "gam_log_ior_lower90", score_type_auc = "gam_log_ior"),
  list(nombre = "GAM-RERI", tipo = "RERI", null = TRUE,
       score_type = "gam_reri_lower90", score_type_auc = "gam_reri"),
  # GAM nominal (no null threshold)
  list(nombre = "GAM-logIOR_nom", tipo = "IOR", null = FALSE,
       score_type = "gam_log_ior_lower90", score_type_auc = "gam_log_ior"),
  list(nombre = "GAM-RERI_nom", tipo = "RERI", null = FALSE,
       score_type = "gam_reri_lower90", score_type_auc = "gam_reri"),
  # Stratified nominal
  list(nombre = "Estratificado-IOR", tipo = "IOR", null = FALSE,
       score_type = "classic_log_ior_lower90", score_type_auc = "classic_log_ior"),
  list(nombre = "Estratificado-RERI", tipo = "RERI", null = FALSE,
       score_type = "classic_reri_lower90", score_type_auc = "classic_reri"),
  # Stratified with null distribution threshold (requires 20_null classic outputs)
  list(nombre = "Estratificado-IOR_null", tipo = "IOR", null = classic_null_available,
       score_type = "classic_log_ior_lower90", score_type_auc = "classic_log_ior"),
  list(nombre = "Estratificado-RERI_null", tipo = "RERI", null = classic_null_available,
       score_type = "classic_reri_lower90", score_type_auc = "classic_reri")
)

################################################################################
# Metrics calculation
################################################################################

# Original metrics (no power-based filtering applied to positive triplets)
res_global_original <- list()
res_dinamica_original <- list()
res_etapa_original <- list()

for (red_pct in reduction_levels) {
  
  message(sprintf("\nReducción %d%%", red_pct)) # reduction level tracking
  datos <- datos_por_reduccion[[as.character(red_pct)]]
  
  for (met in metodos) {
    
    message(sprintf("  %s", met$nombre))
    
    # Global metrics
    # Filter negatives to high-reporting stages only
    etapas_alto_reporte <- stage_class[class == 1, unique(nichd)]
    neg_global <- datos$neg_high[nichd %in% etapas_alto_reporte]

    dt_global <- rbind(datos$pos_high, neg_global, fill = TRUE)
    dt_global <- detect_signal(dt_global, met$nombre, met$tipo, use_null = met$null)
    
    # aggregate at triplet level for global metrics
    metrics_global <- calculate_metrics(dt_global, n_boot, aggregate_triplet = TRUE,  # TRUE here to avoid double-counting across stages
      score_type = met$score_type, score_type_auc = met$score_type_auc)
      metrics_global[, `:=`( method = met$nombre, reduction_pct = red_pct, dataset = "original")]
      res_global_original[[length(res_global_original) + 1]] <- metrics_global
    
    # Metrics by dynamic pattern
    dinamicas <- setdiff(unique(datos$pos_high$dynamic), "uniform") # remove uniform (redundant)
     
    for (dyn in dinamicas) {
      # High-reporting stages for this dynamic pattern
      etapas_altas <- stage_class[dynamic == dyn & class == 1, nichd] 
      pos_dyn <- datos$pos_high[nichd %in% etapas_altas & dynamic == dyn]
  
      # Negatives restricted to the same high-reporting stages
      neg_dyn <- datos$neg_high[nichd %in% etapas_altas]
  
      dt_dyn <- rbind(pos_dyn, neg_dyn, fill = TRUE)
      dt_dyn <- detect_signal(dt_dyn, met$nombre, met$tipo, use_null = met$null)
      
      metrics_dyn <- calculate_metrics(dt_dyn, n_boot, aggregate_triplet = TRUE, 
        score_type = met$score_type, score_type_auc = met$score_type_auc) 
      metrics_dyn[, `:=`(
        method = met$nombre,
        reduction_pct = red_pct,
        dynamic = dyn,
        dataset = "original"
      )]
      res_dinamica_original[[length(res_dinamica_original) + 1]] <- metrics_dyn
    }
    
    # Per-stage metrics (no triplet aggregation — evaluated stage-by-stage)
    for (s in 1:7) {
      nichd_label <- niveles_nichd[s]
      
      # Positives: only stages classified as high-reporting (redundant filter for consistency)
      pos_stage <- datos$pos_high[stage_num == s & class == 1]
      
      # Negatives from the same stage
      neg_stage <- datos$neg_high[stage_num == s]
      
      dt_stage <- rbind(pos_stage, neg_stage, fill = TRUE)
      dt_stage <- detect_signal(dt_stage, met$nombre, met$tipo, use_null = met$null)
      
      # no aggregation - each row corresponds to a specific stage
      metrics_stage <- calculate_metrics(dt_stage, n_boot, aggregate_triplet = FALSE, 
        score_type = met$score_type, score_type_auc = met$score_type_auc)
        metrics_stage[, `:=`(method = met$nombre, reduction_pct = red_pct, stage_num = s, nichd = nichd_label, dataset = "original")]
        res_etapa_original[[length(res_etapa_original) + 1]] <- metrics_stage
    }
  }
}

metrics_global_original <- rbindlist(res_global_original, fill = TRUE)
metrics_dynamic_original <- rbindlist(res_dinamica_original, fill = TRUE)
metrics_stage_original <- rbindlist(res_etapa_original, fill = TRUE)

fwrite(metrics_global_original, paste0(output_dir, "metrics_global_original.csv"))
fwrite(metrics_dynamic_original, paste0(output_dir, "metrics_dynamic_original.csv"))
fwrite(metrics_stage_original, paste0(output_dir, "metrics_stage_original.csv"))

################################################################################
# Metrics calculation on the statistical power subset
################################################################################

res_global_filtered <- list()
res_dinamica_filtered <- list()
res_etapa_filtered <- list()

for (red_pct in reduction_levels) {
  
  message(sprintf("\nReducción %d%%", red_pct)) # progress tracking
  datos <- datos_por_reduccion[[as.character(red_pct)]]
  
  for (met in metodos) {
    # progress tracking
    message(sprintf("  %s", met$nombre))
    
    ids_filtrar <- power_ids[[met$nombre]]
    
    # Filtered global metrics
    etapas_alto_reporte <- stage_class[class == 1, unique(nichd)]
    neg_global <- datos$neg_high[nichd %in% etapas_alto_reporte]

    pos_fil <- datos$pos_high[triplet_id %in% ids_filtrar]
    dt_global <- rbind(pos_fil, neg_global, fill = TRUE)
    dt_global <- detect_signal(dt_global, met$nombre, met$tipo, use_null = met$null)
    
    metrics_global <- calculate_metrics(dt_global, n_boot, aggregate_triplet = TRUE, 
      score_type = met$score_type, score_type_auc = met$score_type_auc)
      metrics_global[, `:=`( method = met$nombre, reduction_pct = red_pct, dataset = "filtered")]
      res_global_filtered[[length(res_global_filtered) + 1]] <- metrics_global
    
    # Filtered metrics by dynamic pattern
    dinamicas <- setdiff(unique(datos$pos_high$dynamic), "uniform") # (redundant)
    
    for (dyn in dinamicas) {
      etapas_altas <- stage_class[dynamic == dyn & class == 1, nichd]
      pos_dyn <- datos$pos_high[triplet_id %in% ids_filtrar & nichd %in% etapas_altas & dynamic == dyn]
      
      neg_dyn <- datos$neg_high[nichd %in% etapas_altas]  
      dt_dyn <- rbind(pos_dyn, neg_dyn, fill = TRUE) 
      dt_dyn <- detect_signal(dt_dyn, met$nombre, met$tipo, use_null = met$null)
      
      metrics_dyn <- calculate_metrics(dt_dyn, n_boot, aggregate_triplet = TRUE, 
        score_type = met$score_type, score_type_auc = met$score_type_auc)
        metrics_dyn[, `:=`( method = met$nombre, reduction_pct = red_pct, dynamic = dyn, dataset = "filtered")]
        res_dinamica_filtered[[length(res_dinamica_filtered) + 1]] <- metrics_dyn
    }
    
    # Filtered per-stage metrics
    for (s in 1:7) {
      nichd_label <- niveles_nichd[s]
      pos_stage <- datos$pos_high[triplet_id %in% ids_filtrar & stage_num == s & class == 1]
      
      neg_stage <- datos$neg_high[stage_num == s]
      
      dt_stage <- rbind(pos_stage, neg_stage, fill = TRUE)
      dt_stage <- detect_signal(dt_stage, met$nombre, met$tipo, use_null = met$null)
      
      metrics_stage <- calculate_metrics(dt_stage, n_boot, aggregate_triplet = FALSE, 
        score_type = met$score_type, score_type_auc = met$score_type_auc)
      metrics_stage[, `:=`(
        method = met$nombre,
        reduction_pct = red_pct,
        stage_num = s,
        nichd = nichd_label,
        dataset = "filtered"
      )]
      res_etapa_filtered[[length(res_etapa_filtered) + 1]] <- metrics_stage
    }
  }
}

metrics_global_filtered <- rbindlist(res_global_filtered, fill = TRUE)
metrics_dynamic_filtered <- rbindlist(res_dinamica_filtered, fill = TRUE)
metrics_stage_filtered <- rbindlist(res_etapa_filtered, fill = TRUE)

fwrite(metrics_global_filtered, paste0(output_dir, "metrics_global_filtered.csv"))
fwrite(metrics_dynamic_filtered, paste0(output_dir, "metrics_dynamic_filtered.csv"))
fwrite(metrics_stage_filtered, paste0(output_dir, "metrics_stage_filtered.csv"))

################################################################################
# Metrics calculation on the intersection subset
################################################################################

pares_interseccion <- list(
  list(
    metodos = metodos[sapply(metodos, function(m) m$nombre %in% c("GAM-RERI", "Estratificado-RERI"))],
    triplets = triplets_intersection_reri,
    label = "RERI"
  ),
  list(
    metodos = metodos[sapply(metodos, function(m) m$nombre %in% c("GAM-logIOR", "Estratificado-IOR"))],
    triplets = triplets_intersection_ior,
    label = "IOR"
  )
)

res_global_inter <- list()
res_dinamica_inter <- list()
res_etapa_inter <- list()

for (red_pct in reduction_levels) {
  message(sprintf("\nReducción %d%%", red_pct))
  datos <- datos_por_reduccion[[as.character(red_pct)]]
  
  for (par in pares_interseccion) {
    for (met in par$metodos) {
      message(sprintf("%s [intersección %s]", met$nombre, par$label))
      
      pos_int <- datos$pos_high[triplet_id %in% par$triplets]   # use the pair-specific intersection triplet set
      
      # Global metrics
      etapas_alto_reporte <- stage_class[class == 1, unique(nichd)]
      neg_global <- datos$neg_high[nichd %in% etapas_alto_reporte]
      dt_global <- rbind(pos_int, neg_global, fill = TRUE)
      dt_global <- detect_signal(dt_global, met$nombre, met$tipo, use_null = met$null)
      
      metrics_global <- calculate_metrics(dt_global, n_boot, aggregate_triplet = TRUE, score_type = met$score_type, score_type_auc = met$score_type_auc)
      metrics_global[, `:=`(method = met$nombre, reduction_pct = red_pct, dataset = "intersection")]
      res_global_inter[[length(res_global_inter) + 1]] <- metrics_global
      
      # Metrics by dynamic pattern
      dinamicas <- setdiff(unique(datos$pos_high$dynamic), "uniform")
      for (dyn in dinamicas) {
        etapas_altas <- stage_class[dynamic == dyn & class == 1, nichd]
        pos_dyn <- pos_int[nichd %in% etapas_altas & dynamic == dyn]
        neg_dyn <- datos$neg_high[nichd %in% etapas_altas]
        dt_dyn <- rbind(pos_dyn, neg_dyn, fill = TRUE)
        dt_dyn <- detect_signal(dt_dyn, met$nombre, met$tipo, use_null = met$null)
        
        metrics_dyn <- calculate_metrics(dt_dyn, n_boot, aggregate_triplet = TRUE,
          score_type = met$score_type, score_type_auc = met$score_type_auc)
        metrics_dyn[, `:=`(method = met$nombre, reduction_pct = red_pct, dynamic = dyn, dataset = "intersection")]
        res_dinamica_inter[[length(res_dinamica_inter) + 1]] <- metrics_dyn
      }
      
      # Per-stage metrics
      for (s in 1:7) {
        nichd_label <- niveles_nichd[s]
        pos_stage <- pos_int[stage_num == s & class == 1]
        neg_stage <- datos$neg_high[stage_num == s]
        dt_stage <- rbind(pos_stage, neg_stage, fill = TRUE)
        dt_stage <- detect_signal(dt_stage, met$nombre, met$tipo, use_null = met$null)
        
        metrics_stage <- calculate_metrics(dt_stage, n_boot, aggregate_triplet = FALSE,
          score_type = met$score_type, score_type_auc = met$score_type_auc)
        metrics_stage[, `:=`(method = met$nombre, reduction_pct = red_pct,
                             stage_num = s, nichd = nichd_label, dataset = "intersection")]
        res_etapa_inter[[length(res_etapa_inter) + 1]] <- metrics_stage
      }
    }
  }
}

metrics_global_intersection <- rbindlist(res_global_inter, fill = TRUE)
metrics_dynamic_intersection <- rbindlist(res_dinamica_inter, fill = TRUE)
metrics_stage_intersection <- rbindlist(res_etapa_inter, fill = TRUE)

fwrite(metrics_global_intersection,  paste0(output_dir, "metrics_global_intersection.csv"))
fwrite(metrics_dynamic_intersection, paste0(output_dir, "metrics_dynamic_intersection.csv"))
fwrite(metrics_stage_intersection,   paste0(output_dir, "metrics_stage_intersection.csv"))
